from __future__ import annotations

import uuid
from pathlib import Path
from typing import Annotated, Any, Literal

from fastapi import APIRouter, Header, Request
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from app.core.storage import STORE_LOCK, data_path, read_json, write_json_atomic

router = APIRouter(tags=["UserCards"])

# Must match app/domain/models.py PaymentMethod — not CREDIT_CARD/DEBIT_CARD
PaymentMethod = Literal["CREDIT", "DEBIT"]

_DEFAULT_PREFS = {"notify_expiring": False, "notify_new": False}
_MAX_CARDS = 20

# Anonymous per-browser identifier generated by the client (a UUID) and sent on
# every request. It namespaces stored data; it is not an authentication secret.
SessionId = Annotated[str, Header(alias="X-Session-Id", pattern=r"^[A-Za-z0-9-]{16,64}$")]


# ── Request / Response models ───────────────────────────────────────────────


class SaveCardRequest(BaseModel):
    bank_id: str = Field(min_length=1, max_length=50)
    card_name: str | None = Field(default=None, max_length=120)
    payment_method: PaymentMethod


class CardRecord(BaseModel):
    card_id: str
    bank_id: str
    card_name: str | None
    payment_method: PaymentMethod


class NotificationPrefsRequest(BaseModel):
    notify_expiring: bool
    notify_new: bool


# ── Helpers ─────────────────────────────────────────────────────────────────


def _user_file(session_id: str) -> Path:
    return data_path("user_cards", f"{session_id}.json")


def _load_user(session_id: str) -> dict[str, Any]:
    data = read_json(_user_file(session_id), {})
    if not isinstance(data, dict):
        data = {}
    cards = data.get("cards")
    prefs = data.get("prefs")
    return {
        "cards": cards if isinstance(cards, list) else [],
        "prefs": {
            "notify_expiring": bool(prefs.get("notify_expiring", False)) if isinstance(prefs, dict) else False,
            "notify_new": bool(prefs.get("notify_new", False)) if isinstance(prefs, dict) else False,
        },
    }


def _not_enabled_response():
    return JSONResponse(status_code=404, content={"error": {"code": "NOT_FOUND"}})


# ── Card endpoints ───────────────────────────────────────────────────────────


@router.post("/user/cards")
def save_card(request: Request, body: SaveCardRequest, session_id: SessionId):
    flags = request.app.state.feature_flags
    if flags is None or not flags.userCardsEnabled:
        return _not_enabled_response()

    with STORE_LOCK:
        user = _load_user(session_id)
        if len(user["cards"]) >= _MAX_CARDS:
            return JSONResponse(
                status_code=422,
                content={"error": {"code": "CARD_LIMIT_REACHED", "message": f"Maximum {_MAX_CARDS} cards allowed"}},
            )
        record = {
            "card_id": str(uuid.uuid4()),
            "bank_id": body.bank_id,
            "card_name": body.card_name,
            "payment_method": body.payment_method,
        }
        user["cards"].append(record)
        write_json_atomic(_user_file(session_id), user)
    return record


@router.get("/user/cards")
def list_cards(request: Request, session_id: SessionId):
    flags = request.app.state.feature_flags
    if flags is None or not flags.userCardsEnabled:
        return _not_enabled_response()

    with STORE_LOCK:
        return {"cards": _load_user(session_id)["cards"]}


@router.delete("/user/cards/{card_id}")
def delete_card(card_id: str, request: Request, session_id: SessionId):
    flags = request.app.state.feature_flags
    if flags is None or not flags.userCardsEnabled:
        return _not_enabled_response()

    with STORE_LOCK:
        user = _load_user(session_id)
        remaining = [c for c in user["cards"] if c.get("card_id") != card_id]
        if len(remaining) == len(user["cards"]):
            return JSONResponse(status_code=404, content={"error": {"code": "NOT_FOUND", "message": "Card not found"}})
        user["cards"] = remaining
        write_json_atomic(_user_file(session_id), user)
    return {"deleted": True}


# ── Notification prefs endpoints ─────────────────────────────────────────────


@router.post("/user/notification-prefs")
def save_notification_prefs(request: Request, body: NotificationPrefsRequest, session_id: SessionId):
    flags = request.app.state.feature_flags
    if flags is None or not flags.notificationsEnabled:
        return _not_enabled_response()

    with STORE_LOCK:
        user = _load_user(session_id)
        user["prefs"] = {"notify_expiring": body.notify_expiring, "notify_new": body.notify_new}
        write_json_atomic(_user_file(session_id), user)
    return {"saved": True}


@router.get("/user/notification-prefs")
def get_notification_prefs(request: Request, session_id: SessionId):
    flags = request.app.state.feature_flags
    if flags is None or not flags.notificationsEnabled:
        return _not_enabled_response()

    with STORE_LOCK:
        return _load_user(session_id)["prefs"]
